name: upload artifact (reusable workflow)
on:
  workflow_call:
jobs:
  upload-artifact:
    runs-on: [ ubuntu-latest ]
    steps:
      - run: echo 'test-data' > data.md
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: data.md
